# Generated by Django 4.2 on 2023-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
