# Generated by Django 4.2 on 2023-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_imagem_alter_pessoa_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='anime',
            field=models.CharField(default='???', max_length=255),
        ),
    ]
