# Generated by Django 4.2 on 2023-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
