# Generated by Django 4.2 on 2023-04-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoa_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='wallpaper',
            field=models.TextField(default='https://wallhaven.cc/w/6kyxel'),
        ),
    ]
