# Generated by Django 4.2 on 2023-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pessoa_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='info',
            field=models.TextField(default='Esse é um personagem ainda não tem uma descrição legal, mete um edit ai comparsa.'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powerimg1',
            field=models.TextField(default='https://i.gifer.com/3tW3.gif'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powerimg2',
            field=models.TextField(default='https://en.dragon-ball-official.com/dragonball/jp/news/2021/11/07_08851834_164.png?_=1680441420'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powerimg3',
            field=models.TextField(default='https://en.dragon-ball-official.com/dragonball/jp/news/2021/11/07_08851834_164.png?_=1680441420'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermove1',
            field=models.CharField(default='Respirar', max_length=255),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermove2',
            field=models.CharField(default='Gritar', max_length=255),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermove3',
            field=models.CharField(default='Fugir', max_length=255),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermovedesc1',
            field=models.TextField(default='Esse personagem tem a capacidade de fazer isso que tá no titulo ;P'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermovedesc2',
            field=models.TextField(default='Em casos de emergencia ele pode fazer isso..'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='powermovedesc3',
            field=models.TextField(default='Habilidade especial caso o personagem saiba que tem uma promoção no mercado xD'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='titulo',
            field=models.CharField(default='Featured', max_length=255),
        ),
    ]
