# Generated by Django 4.2 on 2023-04-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pessoa_powerimg2_alter_pessoa_powerimg3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='powermovedesc1',
            field=models.TextField(default='Eu não sei o que ele vai fazer com tanto O², mais ele é capaz de fazer isso...'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='powermovedesc2',
            field=models.TextField(default='Isso ou pode assustar ou pode transformar a pessoa em um novo astro do POP...'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='powermovedesc3',
            field=models.TextField(default='Habilidade Suprema caso o personagem saiba que tem uma promoção no mercado...'),
        ),
    ]
